//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadFile", ReplyAction="http://tempuri.org/IService1/UploadFileResponse")]
        string UploadFile(System.IO.Stream fileContents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadFile", ReplyAction="http://tempuri.org/IService1/UploadFileResponse")]
        System.Threading.Tasks.Task<string> UploadFileAsync(System.IO.Stream fileContents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestFunction", ReplyAction="http://tempuri.org/IService1/TestFunctionResponse")]
        string TestFunction(string testcont);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestFunction", ReplyAction="http://tempuri.org/IService1/TestFunctionResponse")]
        System.Threading.Tasks.Task<string> TestFunctionAsync(string testcont);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference1.IService1>, ConsoleApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UploadFile(System.IO.Stream fileContents) {
            return base.Channel.UploadFile(fileContents);
        }
        
        public System.Threading.Tasks.Task<string> UploadFileAsync(System.IO.Stream fileContents) {
            return base.Channel.UploadFileAsync(fileContents);
        }
        
        public string TestFunction(string testcont) {
            return base.Channel.TestFunction(testcont);
        }
        
        public System.Threading.Tasks.Task<string> TestFunctionAsync(string testcont) {
            return base.Channel.TestFunctionAsync(testcont);
        }
    }
}
